/* Generated by Yosys 0.61+21 (git sha1 2bde91b6e, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module bist_alu_top(clk, reset, bist_start, a, b, op, normal_enable, power_mode, bist_power_enable, y, bist_done, bist_pass);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input bist_start;
  wire bist_start;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input [2:0] op;
  wire [2:0] op;
  input normal_enable;
  wire normal_enable;
  input power_mode;
  wire power_mode;
  input bist_power_enable;
  wire bist_power_enable;
  output [7:0] y;
  wire [7:0] y;
  output bist_done;
  wire bist_done;
  output bist_pass;
  wire bist_pass;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire [7:0] _228_;
  wire [7:0] alu_y;
  wire [7:0] alu_y_retention;
  wire bist_active;
  wire [7:0] lfsr_out;
  wire [7:0] signature;
  wire \u_alu.clk ;
  wire \u_alu.clk_en ;
  wire \u_alu.power_mode ;
  wire [7:0] \u_alu.y ;
  wire [7:0] \u_alu.y_retention ;
  wire \u_cmp.clk ;
  wire \u_cmp.enable ;
  wire \u_cmp.pass_reg ;
  wire \u_cmp.registered_mode ;
  wire [7:0] \u_cmp.signature ;
  wire \u_ctrl.bist_active ;
  wire \u_ctrl.clk ;
  wire [4:0] \u_ctrl.count ;
  wire \u_ctrl.done ;
  wire \u_ctrl.reset ;
  wire \u_ctrl.start ;
  wire [2:0] \u_ctrl.state ;
  wire \u_misr.clk ;
  wire [7:0] \u_misr.data_in ;
  wire \u_misr.reset ;
  wire [7:0] \u_misr.signature ;
  wire \u_randgen.clk ;
  wire \u_randgen.reset ;
  wire [7:0] \u_randgen.rnd ;
  sky130_fd_sc_hd__clkinv_1 _229_ (
    .A(bist_active),
    .Y(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _230_ (
    .A(power_mode),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _231_ (
    .A(op[2]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _232_ (
    .A(reset),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(bist_power_enable),
    .B(power_mode),
    .Y(_059_)
  );
  sky130_fd_sc_hd__and3_1 _234_ (
    .A(bist_active),
    .B(bist_power_enable),
    .C(power_mode),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand3_1 _235_ (
    .A(bist_active),
    .B(bist_power_enable),
    .C(power_mode),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(\u_randgen.rnd [6]),
    .B(_060_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(\u_randgen.rnd [7]),
    .B(_061_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _238_ (
    .A(_062_),
    .B(_063_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(\u_randgen.rnd [5]),
    .B(_060_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(\u_randgen.rnd [6]),
    .B(_061_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _241_ (
    .A(_064_),
    .B(_065_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(\u_randgen.rnd [4]),
    .B(_060_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(\u_randgen.rnd [5]),
    .B(_061_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _244_ (
    .A(_066_),
    .B(_067_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(\u_randgen.rnd [3]),
    .B(_060_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(\u_randgen.rnd [4]),
    .B(_061_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(_068_),
    .B(_069_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(\u_randgen.rnd [2]),
    .B(_060_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(\u_randgen.rnd [3]),
    .B(_061_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _250_ (
    .A(_070_),
    .B(_071_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(\u_randgen.rnd [1]),
    .B(_060_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(\u_randgen.rnd [2]),
    .B(_061_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(_072_),
    .B(_073_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(\u_randgen.rnd [0]),
    .B(_060_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(\u_randgen.rnd [1]),
    .B(_061_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(_074_),
    .B(_075_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _257_ (
    .A(\u_randgen.rnd [0]),
    .B(_060_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__xnor2_1 _258_ (
    .A(\u_randgen.rnd [4]),
    .B(\u_randgen.rnd [3]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(\u_randgen.rnd [7]),
    .B(\u_randgen.rnd [5]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__xnor2_1 _260_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a21oi_1 _261_ (
    .A1(_060_),
    .A2(_079_),
    .B1(_076_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xnor2_1 _262_ (
    .A(\u_misr.signature [6]),
    .B(\u_alu.y [7]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _263_ (
    .A(\u_misr.signature [7]),
    .B(_060_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a21oi_1 _264_ (
    .A1(_060_),
    .A2(_080_),
    .B1(_081_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(\u_misr.signature [5]),
    .B(\u_alu.y [6]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _266_ (
    .A(\u_misr.signature [6]),
    .B(_061_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o21ai_0 _267_ (
    .A1(_061_),
    .A2(_082_),
    .B1(_083_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _268_ (
    .A(\u_misr.signature [4]),
    .B(\u_alu.y [5]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _269_ (
    .A(\u_misr.signature [5]),
    .B(_061_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o21ai_0 _270_ (
    .A1(_061_),
    .A2(_084_),
    .B1(_085_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__xnor2_1 _271_ (
    .A(\u_misr.signature [3]),
    .B(\u_alu.y [4]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _272_ (
    .A(\u_misr.signature [4]),
    .B(_061_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__o21ai_0 _273_ (
    .A1(_061_),
    .A2(_086_),
    .B1(_087_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _274_ (
    .A(\u_misr.signature [2]),
    .B(\u_alu.y [3]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _275_ (
    .A(\u_misr.signature [3]),
    .B(_061_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o21ai_0 _276_ (
    .A1(_061_),
    .A2(_088_),
    .B1(_089_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__xnor2_1 _277_ (
    .A(\u_misr.signature [1]),
    .B(\u_alu.y [2]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _278_ (
    .A(\u_misr.signature [2]),
    .B(_061_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__o21ai_0 _279_ (
    .A1(_061_),
    .A2(_090_),
    .B1(_091_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xnor2_1 _280_ (
    .A(\u_misr.signature [0]),
    .B(\u_alu.y [1]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(\u_misr.signature [1]),
    .B(_061_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21ai_0 _282_ (
    .A1(_061_),
    .A2(_092_),
    .B1(_093_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(\u_alu.y [0]),
    .B(_060_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _284_ (
    .A(\u_misr.signature [0]),
    .B(_061_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(_094_),
    .B(_095_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand3_1 _286_ (
    .A(\u_ctrl.count [2]),
    .B(\u_ctrl.count [1]),
    .C(\u_ctrl.count [0]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand4_1 _287_ (
    .A(\u_ctrl.count [3]),
    .B(\u_ctrl.count [2]),
    .C(\u_ctrl.count [1]),
    .D(\u_ctrl.count [0]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor3_1 _288_ (
    .A(\u_ctrl.count [4]),
    .B(_059_),
    .C(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(bist_active),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _290_ (
    .A(\u_ctrl.state [0]),
    .B(_060_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21o_1 _291_ (
    .A1(_060_),
    .A2(_097_),
    .B1(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _292_ (
    .A(\u_ctrl.count [4]),
    .B(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(_099_),
    .B(_102_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nor2_1 _294_ (
    .A(_061_),
    .B(_096_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o21a_1 _295_ (
    .A1(\u_ctrl.count [3]),
    .A2(_103_),
    .B1(_101_),
    .X(_039_)
  );
  sky130_fd_sc_hd__a31oi_1 _296_ (
    .A1(\u_ctrl.count [1]),
    .A2(\u_ctrl.count [0]),
    .A3(_060_),
    .B1(\u_ctrl.count [2]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a211oi_1 _297_ (
    .A1(\u_ctrl.state [0]),
    .A2(_061_),
    .B1(_103_),
    .C1(_104_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _298_ (
    .A(\u_ctrl.count [1]),
    .B(\u_ctrl.count [0]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a21oi_1 _299_ (
    .A1(\u_ctrl.count [1]),
    .A2(\u_ctrl.count [0]),
    .B1(_061_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21oi_1 _300_ (
    .A1(\u_ctrl.count [1]),
    .A2(_100_),
    .B1(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(_105_),
    .B(_107_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(\u_ctrl.count [0]),
    .B(_100_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o21ai_0 _303_ (
    .A1(\u_ctrl.count [0]),
    .A2(_061_),
    .B1(_108_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o21ai_0 _304_ (
    .A1(bist_active),
    .A2(normal_enable),
    .B1(power_mode),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _305_ (
    .A(_109_),
    .Y(\u_alu.clk_en )
  );
  sky130_fd_sc_hd__o21ai_0 _306_ (
    .A1(bist_start),
    .A2(_059_),
    .B1(bist_done),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(_099_),
    .B(_110_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand4_1 _308_ (
    .A(bist_power_enable),
    .B(power_mode),
    .C(\u_ctrl.state [0]),
    .D(bist_start),
    .Y(_111_)
  );
  sky130_fd_sc_hd__o21ai_0 _309_ (
    .A1(_057_),
    .A2(_098_),
    .B1(_111_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a31oi_1 _310_ (
    .A1(bist_power_enable),
    .A2(power_mode),
    .A3(bist_done),
    .B1(\u_ctrl.state [0]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a31oi_1 _311_ (
    .A1(bist_power_enable),
    .A2(power_mode),
    .A3(bist_start),
    .B1(_112_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _312_ (
    .A0(\u_alu.y_retention [0]),
    .A1(\u_alu.y [0]),
    .S(power_mode),
    .X(y[0])
  );
  sky130_fd_sc_hd__mux2_1 _313_ (
    .A0(\u_alu.y_retention [1]),
    .A1(\u_alu.y [1]),
    .S(power_mode),
    .X(y[1])
  );
  sky130_fd_sc_hd__mux2_1 _314_ (
    .A0(\u_alu.y_retention [2]),
    .A1(\u_alu.y [2]),
    .S(power_mode),
    .X(y[2])
  );
  sky130_fd_sc_hd__mux2_1 _315_ (
    .A0(\u_alu.y_retention [3]),
    .A1(\u_alu.y [3]),
    .S(power_mode),
    .X(y[3])
  );
  sky130_fd_sc_hd__mux2_1 _316_ (
    .A0(\u_alu.y_retention [4]),
    .A1(\u_alu.y [4]),
    .S(power_mode),
    .X(y[4])
  );
  sky130_fd_sc_hd__mux2_1 _317_ (
    .A0(\u_alu.y_retention [5]),
    .A1(\u_alu.y [5]),
    .S(power_mode),
    .X(y[5])
  );
  sky130_fd_sc_hd__mux2_1 _318_ (
    .A0(\u_alu.y_retention [6]),
    .A1(\u_alu.y [6]),
    .S(power_mode),
    .X(y[6])
  );
  sky130_fd_sc_hd__mux2_1 _319_ (
    .A0(\u_alu.y_retention [7]),
    .A1(\u_alu.y [7]),
    .S(power_mode),
    .X(y[7])
  );
  sky130_fd_sc_hd__nor2_1 _320_ (
    .A(bist_active),
    .B(b[0]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a211oi_1 _321_ (
    .A1(\u_randgen.rnd [0]),
    .A2(_060_),
    .B1(_109_),
    .C1(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _322_ (
    .A(normal_enable),
    .SLEEP(bist_active),
    .X(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _323_ (
    .A(a[0]),
    .B(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand3_1 _324_ (
    .A(a[0]),
    .B(_114_),
    .C(_115_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2b_1 _325_ (
    .A_N(bist_active),
    .B(op[1]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__or3_1 _326_ (
    .A(op[0]),
    .B(op[2]),
    .C(_118_),
    .X(_119_)
  );
  sky130_fd_sc_hd__nor3b_1 _327_ (
    .A(op[2]),
    .B(_118_),
    .C_N(op[0]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o21ai_0 _328_ (
    .A1(bist_active),
    .A2(_058_),
    .B1(_118_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o21ai_0 _329_ (
    .A1(op[0]),
    .A2(op[1]),
    .B1(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a21oi_1 _330_ (
    .A1(_117_),
    .A2(_122_),
    .B1(_120_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a211o_1 _331_ (
    .A1(_113_),
    .A2(_116_),
    .B1(_123_),
    .C1(_109_),
    .X(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _332_ (
    .A1(_117_),
    .A2(_119_),
    .B1(_124_),
    .Y(_228_[0])
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(_114_),
    .B(_116_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(a[1]),
    .B(_115_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a21oi_1 _335_ (
    .A1(_072_),
    .A2(_126_),
    .B1(_109_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor2_1 _336_ (
    .A(bist_active),
    .B(b[1]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a211oi_1 _337_ (
    .A1(\u_randgen.rnd [1]),
    .A2(_060_),
    .B1(_109_),
    .C1(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor4b_1 _338_ (
    .A(bist_active),
    .B(op[1]),
    .C(op[2]),
    .D_N(op[0]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand4_1 _339_ (
    .A(_057_),
    .B(op[0]),
    .C(_058_),
    .D(_118_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a2111oi_0 _340_ (
    .A1(\u_randgen.rnd [0]),
    .A2(_060_),
    .B1(_109_),
    .C1(_113_),
    .D1(_130_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__xnor2_1 _341_ (
    .A(_129_),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xor2_1 _342_ (
    .A(_127_),
    .B(_133_),
    .X(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _343_ (
    .A1(_125_),
    .A2(_134_),
    .B1(_121_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _344_ (
    .A1(_125_),
    .A2(_134_),
    .B1(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand3_1 _345_ (
    .A(a[1]),
    .B(_115_),
    .C(_129_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__or4_1 _346_ (
    .A(bist_active),
    .B(op[0]),
    .C(op[1]),
    .D(_058_),
    .X(_138_)
  );
  sky130_fd_sc_hd__a31oi_1 _347_ (
    .A1(a[1]),
    .A2(_115_),
    .A3(_129_),
    .B1(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o22ai_1 _348_ (
    .A1(_127_),
    .A2(_129_),
    .B1(_139_),
    .B2(_120_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o211ai_1 _349_ (
    .A1(_119_),
    .A2(_137_),
    .B1(_140_),
    .C1(_136_),
    .Y(_228_[1])
  );
  sky130_fd_sc_hd__maj3_1 _350_ (
    .A(_125_),
    .B(_127_),
    .C(_133_),
    .X(_141_)
  );
  sky130_fd_sc_hd__nand2_1 _351_ (
    .A(a[2]),
    .B(_115_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _352_ (
    .A1(_070_),
    .A2(_142_),
    .B1(_109_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor2_1 _353_ (
    .A(bist_active),
    .B(b[2]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a211oi_1 _354_ (
    .A1(\u_randgen.rnd [2]),
    .A2(_060_),
    .B1(_109_),
    .C1(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_0 _355_ (
    .A1(_114_),
    .A2(_129_),
    .B1(_131_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__xor2_1 _356_ (
    .A(_145_),
    .B(_146_),
    .X(_147_)
  );
  sky130_fd_sc_hd__xor2_1 _357_ (
    .A(_143_),
    .B(_147_),
    .X(_148_)
  );
  sky130_fd_sc_hd__a21oi_1 _358_ (
    .A1(_141_),
    .A2(_148_),
    .B1(_121_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21ai_0 _359_ (
    .A1(_141_),
    .A2(_148_),
    .B1(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand3_1 _360_ (
    .A(a[2]),
    .B(_115_),
    .C(_145_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a31oi_1 _361_ (
    .A1(a[2]),
    .A2(_115_),
    .A3(_145_),
    .B1(_138_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o22ai_1 _362_ (
    .A1(_143_),
    .A2(_145_),
    .B1(_152_),
    .B2(_120_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o211ai_1 _363_ (
    .A1(_119_),
    .A2(_151_),
    .B1(_153_),
    .C1(_150_),
    .Y(_228_[2])
  );
  sky130_fd_sc_hd__maj3_1 _364_ (
    .A(_141_),
    .B(_143_),
    .C(_147_),
    .X(_154_)
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(a[3]),
    .B(_115_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a21oi_1 _366_ (
    .A1(_068_),
    .A2(_155_),
    .B1(_109_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o21ai_0 _367_ (
    .A1(bist_active),
    .A2(b[3]),
    .B1(\u_alu.clk_en ),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a21oi_1 _368_ (
    .A1(\u_randgen.rnd [3]),
    .A2(_060_),
    .B1(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o31ai_1 _369_ (
    .A1(_114_),
    .A2(_129_),
    .A3(_145_),
    .B1(_131_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xor2_1 _370_ (
    .A(_158_),
    .B(_159_),
    .X(_160_)
  );
  sky130_fd_sc_hd__and2_0 _371_ (
    .A(_156_),
    .B(_160_),
    .X(_161_)
  );
  sky130_fd_sc_hd__xor2_1 _372_ (
    .A(_156_),
    .B(_160_),
    .X(_162_)
  );
  sky130_fd_sc_hd__a21oi_1 _373_ (
    .A1(_154_),
    .A2(_162_),
    .B1(_121_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o21ai_0 _374_ (
    .A1(_154_),
    .A2(_162_),
    .B1(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand3_1 _375_ (
    .A(a[3]),
    .B(_115_),
    .C(_158_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a31oi_1 _376_ (
    .A1(a[3]),
    .A2(_115_),
    .A3(_158_),
    .B1(_138_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o22ai_1 _377_ (
    .A1(_156_),
    .A2(_158_),
    .B1(_166_),
    .B2(_120_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o211ai_1 _378_ (
    .A1(_119_),
    .A2(_165_),
    .B1(_167_),
    .C1(_164_),
    .Y(_228_[3])
  );
  sky130_fd_sc_hd__a21oi_1 _379_ (
    .A1(_154_),
    .A2(_162_),
    .B1(_161_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _380_ (
    .A(a[4]),
    .B(_115_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a21oi_1 _381_ (
    .A1(_066_),
    .A2(_169_),
    .B1(_109_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__clkinv_1 _382_ (
    .A(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__o21ai_0 _383_ (
    .A1(bist_active),
    .A2(b[4]),
    .B1(\u_alu.clk_en ),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _384_ (
    .A1(\u_randgen.rnd [4]),
    .A2(_060_),
    .B1(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__clkinv_1 _385_ (
    .A(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor4_1 _386_ (
    .A(_114_),
    .B(_129_),
    .C(_145_),
    .D(_158_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(_130_),
    .B(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__xnor2_1 _388_ (
    .A(_174_),
    .B(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__xnor2_1 _389_ (
    .A(_171_),
    .B(_177_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a21oi_1 _390_ (
    .A1(_168_),
    .A2(_178_),
    .B1(_121_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__o21ai_0 _391_ (
    .A1(_168_),
    .A2(_178_),
    .B1(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__a31oi_1 _392_ (
    .A1(a[4]),
    .A2(_115_),
    .A3(_173_),
    .B1(_138_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__o22ai_1 _393_ (
    .A1(_170_),
    .A2(_173_),
    .B1(_181_),
    .B2(_120_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__o311ai_0 _394_ (
    .A1(_119_),
    .A2(_169_),
    .A3(_174_),
    .B1(_180_),
    .C1(_182_),
    .Y(_228_[4])
  );
  sky130_fd_sc_hd__maj3_1 _395_ (
    .A(_168_),
    .B(_171_),
    .C(_177_),
    .X(_183_)
  );
  sky130_fd_sc_hd__nand2_1 _396_ (
    .A(a[5]),
    .B(_115_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__a21oi_1 _397_ (
    .A1(_064_),
    .A2(_184_),
    .B1(_109_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__o21ai_0 _398_ (
    .A1(bist_active),
    .A2(b[5]),
    .B1(\u_alu.clk_en ),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a21oi_1 _399_ (
    .A1(\u_randgen.rnd [5]),
    .A2(_060_),
    .B1(_186_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a21oi_1 _400_ (
    .A1(_174_),
    .A2(_175_),
    .B1(_130_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__xnor2_1 _401_ (
    .A(_187_),
    .B(_188_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand2_1 _402_ (
    .A(_185_),
    .B(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _403_ (
    .A(_185_),
    .B(_189_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _404_ (
    .A(_190_),
    .SLEEP(_191_),
    .X(_192_)
  );
  sky130_fd_sc_hd__xor2_1 _405_ (
    .A(_183_),
    .B(_192_),
    .X(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(_185_),
    .B(_187_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__a21oi_1 _407_ (
    .A1(_185_),
    .A2(_187_),
    .B1(_138_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__o22ai_1 _408_ (
    .A1(_185_),
    .A2(_187_),
    .B1(_195_),
    .B2(_120_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__o221ai_1 _409_ (
    .A1(_121_),
    .A2(_193_),
    .B1(_194_),
    .B2(_119_),
    .C1(_196_),
    .Y(_228_[5])
  );
  sky130_fd_sc_hd__o21a_1 _410_ (
    .A1(_183_),
    .A2(_191_),
    .B1(_190_),
    .X(_197_)
  );
  sky130_fd_sc_hd__nand2_1 _411_ (
    .A(a[6]),
    .B(_115_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__a21oi_1 _412_ (
    .A1(_062_),
    .A2(_198_),
    .B1(_109_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__o21ai_0 _413_ (
    .A1(bist_active),
    .A2(b[6]),
    .B1(\u_alu.clk_en ),
    .Y(_200_)
  );
  sky130_fd_sc_hd__a21oi_1 _414_ (
    .A1(\u_randgen.rnd [6]),
    .A2(_060_),
    .B1(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__a21oi_1 _415_ (
    .A1(_131_),
    .A2(_187_),
    .B1(_188_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__xor2_1 _416_ (
    .A(_201_),
    .B(_202_),
    .X(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _417_ (
    .A(_199_),
    .B(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__xnor2_1 _418_ (
    .A(_199_),
    .B(_203_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _419_ (
    .A(_197_),
    .SLEEP(_205_),
    .X(_206_)
  );
  sky130_fd_sc_hd__a21oi_1 _420_ (
    .A1(_197_),
    .A2(_205_),
    .B1(_121_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand2_1 _421_ (
    .A(_206_),
    .B(_207_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nand3_1 _422_ (
    .A(a[6]),
    .B(_115_),
    .C(_201_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__a31oi_1 _423_ (
    .A1(a[6]),
    .A2(_115_),
    .A3(_201_),
    .B1(_138_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o22ai_1 _424_ (
    .A1(_199_),
    .A2(_201_),
    .B1(_210_),
    .B2(_120_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o211ai_1 _425_ (
    .A1(_119_),
    .A2(_209_),
    .B1(_211_),
    .C1(_208_),
    .Y(_228_[6])
  );
  sky130_fd_sc_hd__nand2_1 _426_ (
    .A(\u_randgen.rnd [7]),
    .B(_060_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(bist_active),
    .B(b[7]),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor2_1 _428_ (
    .A(_109_),
    .B(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nand2_1 _429_ (
    .A(a[7]),
    .B(_115_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__a31oi_1 _430_ (
    .A1(_212_),
    .A2(_213_),
    .A3(_215_),
    .B1(_109_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand4_1 _431_ (
    .A(_057_),
    .B(normal_enable),
    .C(a[7]),
    .D(_214_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand2_1 _432_ (
    .A(_216_),
    .B(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(_131_),
    .B(_201_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nand2_1 _434_ (
    .A(_202_),
    .B(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__xnor2_1 _435_ (
    .A(_218_),
    .B(_220_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__a21oi_1 _436_ (
    .A1(_204_),
    .A2(_206_),
    .B1(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__and3_1 _437_ (
    .A(_204_),
    .B(_206_),
    .C(_221_),
    .X(_223_)
  );
  sky130_fd_sc_hd__nand2_1 _438_ (
    .A(_120_),
    .B(_216_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__o221a_1 _439_ (
    .A1(_119_),
    .A2(_217_),
    .B1(_218_),
    .B2(_138_),
    .C1(_224_),
    .X(_225_)
  );
  sky130_fd_sc_hd__o31ai_1 _440_ (
    .A1(_121_),
    .A2(_222_),
    .A3(_223_),
    .B1(_225_),
    .Y(_228_[7])
  );
  sky130_fd_sc_hd__nand3b_1 _441_ (
    .A_N(\u_misr.signature [1]),
    .B(\u_misr.signature [0]),
    .C(bist_done),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nand4b_1 _442_ (
    .A_N(\u_misr.signature [7]),
    .B(\u_misr.signature [6]),
    .C(\u_misr.signature [4]),
    .D(\u_misr.signature [2]),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nor4_1 _443_ (
    .A(\u_misr.signature [5]),
    .B(\u_misr.signature [3]),
    .C(_226_),
    .D(_227_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _444_ (
    .A(power_mode),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _445_ (
    .A(power_mode),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _446_ (
    .A(power_mode),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _447_ (
    .A(power_mode),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _448_ (
    .A(power_mode),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _449_ (
    .A(power_mode),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _450_ (
    .A(power_mode),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _451_ (
    .A(reset),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _452_ (
    .A(reset),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _453_ (
    .A(reset),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _454_ (
    .A(reset),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _455_ (
    .A(reset),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _456_ (
    .A(reset),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _457_ (
    .A(reset),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _458_ (
    .A(reset),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _459_ (
    .A(reset),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _460_ (
    .A(reset),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _461_ (
    .A(reset),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _462_ (
    .A(reset),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _463_ (
    .A(reset),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _464_ (
    .A(reset),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _465_ (
    .A(reset),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _466_ (
    .A(reset),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _467_ (
    .A(reset),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _468_ (
    .A(reset),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _469_ (
    .A(reset),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _470_ (
    .A(reset),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _471_ (
    .A(reset),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _472_ (
    .A(reset),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _473_ (
    .A(reset),
    .Y(_034_)
  );
  sky130_fd_sc_hd__edfxtp_1 _474_ (
    .CLK(clk),
    .D(\u_alu.y [0]),
    .DE(_003_),
    .Q(\u_alu.y_retention [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _475_ (
    .CLK(clk),
    .D(\u_alu.y [1]),
    .DE(_004_),
    .Q(\u_alu.y_retention [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _476_ (
    .CLK(clk),
    .D(\u_alu.y [2]),
    .DE(_005_),
    .Q(\u_alu.y_retention [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _477_ (
    .CLK(clk),
    .D(\u_alu.y [3]),
    .DE(_006_),
    .Q(\u_alu.y_retention [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _478_ (
    .CLK(clk),
    .D(\u_alu.y [4]),
    .DE(_007_),
    .Q(\u_alu.y_retention [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _479_ (
    .CLK(clk),
    .D(\u_alu.y [5]),
    .DE(_008_),
    .Q(\u_alu.y_retention [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _480_ (
    .CLK(clk),
    .D(\u_alu.y [6]),
    .DE(_009_),
    .Q(\u_alu.y_retention [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _481_ (
    .CLK(clk),
    .D(\u_alu.y [7]),
    .DE(_010_),
    .Q(\u_alu.y_retention [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _482_ (
    .CLK(clk),
    .D(_228_[0]),
    .DE(\u_alu.clk_en ),
    .Q(\u_alu.y [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _483_ (
    .CLK(clk),
    .D(_228_[1]),
    .DE(\u_alu.clk_en ),
    .Q(\u_alu.y [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _484_ (
    .CLK(clk),
    .D(_228_[2]),
    .DE(\u_alu.clk_en ),
    .Q(\u_alu.y [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _485_ (
    .CLK(clk),
    .D(_228_[3]),
    .DE(\u_alu.clk_en ),
    .Q(\u_alu.y [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _486_ (
    .CLK(clk),
    .D(_228_[4]),
    .DE(\u_alu.clk_en ),
    .Q(\u_alu.y [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _487_ (
    .CLK(clk),
    .D(_228_[5]),
    .DE(\u_alu.clk_en ),
    .Q(\u_alu.y [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _488_ (
    .CLK(clk),
    .D(_228_[6]),
    .DE(\u_alu.clk_en ),
    .Q(\u_alu.y [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _489_ (
    .CLK(clk),
    .D(_228_[7]),
    .DE(\u_alu.clk_en ),
    .Q(\u_alu.y [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _490_ (
    .CLK(clk),
    .D(_035_),
    .Q(\u_cmp.pass_reg )
  );
  sky130_fd_sc_hd__dfrtp_1 _491_ (
    .CLK(clk),
    .D(_036_),
    .Q(\u_ctrl.count [0]),
    .RESET_B(_011_)
  );
  sky130_fd_sc_hd__dfrtp_1 _492_ (
    .CLK(clk),
    .D(_037_),
    .Q(\u_ctrl.count [1]),
    .RESET_B(_012_)
  );
  sky130_fd_sc_hd__dfrtp_1 _493_ (
    .CLK(clk),
    .D(_038_),
    .Q(\u_ctrl.count [2]),
    .RESET_B(_013_)
  );
  sky130_fd_sc_hd__dfrtp_1 _494_ (
    .CLK(clk),
    .D(_039_),
    .Q(\u_ctrl.count [3]),
    .RESET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_1 _495_ (
    .CLK(clk),
    .D(_040_),
    .Q(\u_ctrl.count [4]),
    .RESET_B(_015_)
  );
  sky130_fd_sc_hd__dfrtp_1 _496_ (
    .CLK(clk),
    .D(_041_),
    .Q(\u_misr.signature [0]),
    .RESET_B(_016_)
  );
  sky130_fd_sc_hd__dfrtp_1 _497_ (
    .CLK(clk),
    .D(_042_),
    .Q(\u_misr.signature [1]),
    .RESET_B(_017_)
  );
  sky130_fd_sc_hd__dfrtp_1 _498_ (
    .CLK(clk),
    .D(_043_),
    .Q(\u_misr.signature [2]),
    .RESET_B(_018_)
  );
  sky130_fd_sc_hd__dfrtp_1 _499_ (
    .CLK(clk),
    .D(_044_),
    .Q(\u_misr.signature [3]),
    .RESET_B(_019_)
  );
  sky130_fd_sc_hd__dfrtp_1 _500_ (
    .CLK(clk),
    .D(_045_),
    .Q(\u_misr.signature [4]),
    .RESET_B(_020_)
  );
  sky130_fd_sc_hd__dfrtp_1 _501_ (
    .CLK(clk),
    .D(_046_),
    .Q(\u_misr.signature [5]),
    .RESET_B(_021_)
  );
  sky130_fd_sc_hd__dfrtp_1 _502_ (
    .CLK(clk),
    .D(_047_),
    .Q(\u_misr.signature [6]),
    .RESET_B(_022_)
  );
  sky130_fd_sc_hd__dfrtp_1 _503_ (
    .CLK(clk),
    .D(_048_),
    .Q(\u_misr.signature [7]),
    .RESET_B(_023_)
  );
  sky130_fd_sc_hd__dfstp_2 _504_ (
    .CLK(clk),
    .D(_049_),
    .Q(\u_randgen.rnd [0]),
    .SET_B(_024_)
  );
  sky130_fd_sc_hd__dfrtp_1 _505_ (
    .CLK(clk),
    .D(_050_),
    .Q(\u_randgen.rnd [1]),
    .RESET_B(_025_)
  );
  sky130_fd_sc_hd__dfrtp_1 _506_ (
    .CLK(clk),
    .D(_051_),
    .Q(\u_randgen.rnd [2]),
    .RESET_B(_026_)
  );
  sky130_fd_sc_hd__dfrtp_1 _507_ (
    .CLK(clk),
    .D(_052_),
    .Q(\u_randgen.rnd [3]),
    .RESET_B(_027_)
  );
  sky130_fd_sc_hd__dfrtp_1 _508_ (
    .CLK(clk),
    .D(_053_),
    .Q(\u_randgen.rnd [4]),
    .RESET_B(_028_)
  );
  sky130_fd_sc_hd__dfrtp_1 _509_ (
    .CLK(clk),
    .D(_054_),
    .Q(\u_randgen.rnd [5]),
    .RESET_B(_029_)
  );
  sky130_fd_sc_hd__dfrtp_1 _510_ (
    .CLK(clk),
    .D(_055_),
    .Q(\u_randgen.rnd [6]),
    .RESET_B(_030_)
  );
  sky130_fd_sc_hd__dfrtp_1 _511_ (
    .CLK(clk),
    .D(_056_),
    .Q(\u_randgen.rnd [7]),
    .RESET_B(_031_)
  );
  sky130_fd_sc_hd__dfstp_2 _512_ (
    .CLK(clk),
    .D(_000_),
    .Q(\u_ctrl.state [0]),
    .SET_B(_032_)
  );
  sky130_fd_sc_hd__dfrtp_1 _513_ (
    .CLK(clk),
    .D(_001_),
    .Q(bist_active),
    .RESET_B(_033_)
  );
  sky130_fd_sc_hd__dfrtp_1 _514_ (
    .CLK(clk),
    .D(_002_),
    .Q(bist_done),
    .RESET_B(_034_)
  );
  assign alu_y = \u_alu.y ;
  assign alu_y_retention = \u_alu.y_retention ;
  assign bist_pass = \u_cmp.pass_reg ;
  assign lfsr_out = \u_randgen.rnd ;
  assign signature = \u_misr.signature ;
  assign \u_alu.clk  = clk;
  assign \u_alu.power_mode  = power_mode;
  assign \u_cmp.clk  = clk;
  assign \u_cmp.enable  = bist_done;
  assign \u_cmp.registered_mode  = 1'h1;
  assign \u_cmp.signature  = \u_misr.signature ;
  assign \u_ctrl.bist_active  = bist_active;
  assign \u_ctrl.clk  = clk;
  assign \u_ctrl.done  = bist_done;
  assign \u_ctrl.reset  = reset;
  assign \u_ctrl.start  = bist_start;
  assign \u_ctrl.state [2:1] = { bist_done, bist_active };
  assign \u_misr.clk  = clk;
  assign \u_misr.data_in  = \u_alu.y ;
  assign \u_misr.reset  = reset;
  assign \u_randgen.clk  = clk;
  assign \u_randgen.reset  = reset;
endmodule
